// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// basic_factor_matrix
IntegerMatrix basic_factor_matrix(int k);
RcppExport SEXP _doeR_basic_factor_matrix(SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(basic_factor_matrix(k));
    return rcpp_result_gen;
END_RCPP
}
// design_model_matrix
IntegerMatrix design_model_matrix(int k, IntegerVector cols);
RcppExport SEXP _doeR_design_model_matrix(SEXP kSEXP, SEXP colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cols(colsSEXP);
    rcpp_result_gen = Rcpp::wrap(design_model_matrix(k, cols));
    return rcpp_result_gen;
END_RCPP
}
// hamming_distance
int hamming_distance(NumericVector a, NumericVector b);
RcppExport SEXP _doeR_hamming_distance(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(hamming_distance(a, b));
    return rcpp_result_gen;
END_RCPP
}
// distance_distribution
NumericVector distance_distribution(NumericMatrix x);
RcppExport SEXP _doeR_distance_distribution(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(distance_distribution(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_doeR_basic_factor_matrix", (DL_FUNC) &_doeR_basic_factor_matrix, 1},
    {"_doeR_design_model_matrix", (DL_FUNC) &_doeR_design_model_matrix, 2},
    {"_doeR_hamming_distance", (DL_FUNC) &_doeR_hamming_distance, 2},
    {"_doeR_distance_distribution", (DL_FUNC) &_doeR_distance_distribution, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_doeR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
