# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title basic_factor_matrix
#'
#' @description Generate the matrix containing `k` basic factors.
#'
#' @param k Number of basic factors.
#' @return m A \eqn{2^{k} \times k} matrix containing the basic factors.
#' @examples
#' basic_factor_matrix(4)
basic_factor_matrix <- function(k) {
    .Call(`_doeR_basic_factor_matrix`, k)
}

#' Generate the model matrix for the design with `k` factors and the columns
#' specified in the vector ´cols´.
#'
#' @param k Number of basic factors.
#' @param cols Columns used in the design.
#' @return m Design matrix.
design_model_matrix <- function(k, cols) {
    .Call(`_doeR_design_model_matrix`, k, cols)
}

