# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Number of clear 2FI
#'
#' @description Compute the number of clear two-factor interactions (2FI) of a
#' design. A 2FI that is not aliased with any main effect or other 2FI's is
#' called clear.
#'
#' @param X A numeric matrix representing the design matrix.
#' @return An integer represeting the number of clear 2FI in the design.
clear_2fi <- function(X) {
    .Call(`_doeR_clear_2fi`, X)
}

#' @title basic_factor_matrix
#'
#' @description Generate the matrix containing `k` basic factors.
#'
#' @param k Number of basic factors.
#' @return A \eqn{2^{k} \times k} matrix containing the basic factors.
#' @examples
#' \dontrun{
#' basic_factor_matrix(4)
#' }
basic_factor_matrix <- function(k) {
    .Call(`_doeR_basic_factor_matrix`, k)
}

#' Generate the model matrix for the design with `k` factors and the columns
#' specified in the vector ´cols´.
#'
#' @param k Number of basic factors.
#' @param cols Columns used in the design.
#' @return A numeric matrix corresponding to the model matrix of the design.
#' @importFrom Rcpp evalCpp
#' @examples
#' \dontrun{
#' design_model_matrix(4, c(1,2,3,8))
#' }
design_model_matrix <- function(k, cols) {
    .Call(`_doeR_design_model_matrix`, k, cols)
}

#' @title Hamming distance between two vectors
#'
#' @description Computes the hamming distance between two vectors \code{a} and
#' \code{b}. The hamming distance is the number of places where they differ.
#' Therefore, for two vectors of size n, the distance is an integer between 0
#' and n.
#'
#' @param a first vector
#' @param b second vector
#' @return An integer
hamming_distance <- function(a, b) {
    .Call(`_doeR_hamming_distance`, a, b)
}

#' @title Distance distribution of a matrix
#'
#' @description Computes the distribution of the hamming distances between
#' all pairs of rows (even identical) in a matrix. For a matrix with N rows,
#' there are \eqn{\binom{N}{2}+N} such combinations.
#'
#' @details
#' For a matrix \eqn{\mathbf{X}} of size \eqn{(n \times m)}, the distance
#' distribution is a row-vector \eqn{B} of length `n`, where \eqn{B_i} is
#' the number of pairs of rows with hamming distance \eqn{i} divided by `n`.
#' Since pairs of identical rows are considered, \eqn{B_0} will always be `n`.
#'
#' @param x input matrix
#' @return A vector of the distance distribution
distance_distribution <- function(x) {
    .Call(`_doeR_distance_distribution`, x)
}

#' @title Factorial of a number
#'
#' @description Compute the factorial of a number.
#' @param x A positive integer
#' @return A double
factorial <- function(x) {
    .Call(`_doeR_factorial`, x)
}

#' @title Binomial coefficient
#'
#' @description Compute the number of ways of choosing `k` elements out of a
#' set of size `n`. Chosen behavior for negative `k` is to return 0. Chosen
#' behavior for `k` equals to zero is to return 1.
#' @param n An integer, the size of the set of all elements.
#' @param k An integer, the number of elements to choose.
#' @return An integer
nchoosek <- function(n, k) {
    .Call(`_doeR_nchoosek`, n, k)
}

#' @title Krawtchouk polynomials
#'
#' @description Compute the Krawtchouk polynomial P_j(x,n,s) for s=2, since it
#' is for two-level designs.
#' @param j An integer
#' @param x An integer
#' @param n An integer
#' @return An integer giving the value of the polynomial evaluated at j, x and
#' n.
krawtchouk <- function(j, x, n) {
    .Call(`_doeR_krawtchouk`, j, x, n)
}

#' @title MacWilliams Transform
#'
#' @description Compute the MacWiliams transform of the distance distribution
#' of a design.
#' @param B A numeric vector containing the distance distribution of a design.
#' @param N An integer representing the run size of the design.
#' @return A numeric vector of the same size as B.
mac_williams_transform <- function(B, N) {
    .Call(`_doeR_mac_williams_transform`, B, N)
}

#' @title Word length pattern
#'
#' @description Compute the Word Length Pattern (WLP) of a design. For this
#' vector B, B_i represents the number of words of length i.
#'
#' @param D A numeric matrix corresponding to the design matrix.
#' @return A numeric vector with size equal to the number of columns of the
#' original design D, containing the word length pattern.
wlp <- function(D) {
    .Call(`_doeR_wlp`, D)
}

